"""
Employee database model and schemas.
Defines SQLModel table structure and Pydantic schemas for the Employee entity.
"""

from sqlmodel import Field, SQLModel


# ============================================================================
# Database Model
# ============================================================================


class Employee(SQLModel, table=True):
    """
    Employee database table model.
    Represents the employee table in the database with all required fields.
    """

    id: int | None = Field(default=None, primary_key=True)
    name: str = Field(index=True, max_length=255, nullable=False)
    age: int | None = Field(default=None, ge=0, le=150, nullable=True)


# ============================================================================
# Pydantic Request/Response Schemas
# ============================================================================


class EmployeeBase(SQLModel):
    """
    Base employee schema with shared fields.
    Used as foundation for other employee schemas.
    """

    name: str = Field(index=True, max_length=255, min_length=1)
    age: int | None = Field(default=None, ge=0, le=150)


class EmployeeCreate(EmployeeBase):
    """
    Schema for creating a new employee.
    Inherits all required fields from EmployeeBase.
    """

    pass


class EmployeeUpdate(SQLModel):
    """
    Schema for updating an existing employee.
    All fields are optional to support partial updates.
    """

    name: str | None = Field(default=None, max_length=255, min_length=1)
    age: int | None = Field(default=None, ge=0, le=150)


class EmployeePublic(EmployeeBase):
    """
    Schema for employee responses.
    Includes the id field that's generated by the database.
    """

    id: int
