"""
Employee Pydantic schemas.
Defines request/response models for Employee API endpoints.
Separates API contracts from database models for better flexibility.
"""

from sqlmodel import SQLModel, Field  # type: ignore


class EmployeeBase(SQLModel):
    """
    Base employee schema with shared fields.
    Used as foundation for other employee schemas.
    """

    name: str = Field(index=True, max_length=255, min_length=1)
    age: int | None = Field(default=None, ge=0, le=150)


class EmployeeCreate(EmployeeBase):
    """
    Schema for creating a new employee.
    Inherits all required fields from EmployeeBase.
    """

    pass


class EmployeeUpdate(SQLModel):
    """
    Schema for updating an existing employee.
    All fields are optional to support partial updates.
    """

    name: str | None = Field(default=None, max_length=255, min_length=1)
    age: int | None = Field(default=None, ge=0, le=150)


class EmployeePublic(EmployeeBase):
    """
    Schema for employee responses.
    Includes the id field that's generated by the database.
    """

    id: int

    # model_config = {
    #     "json_schema_extra": {
    #         "example": {
    #             "id": 1,
    #             "name": "John Doe",
    #             "age": 30,
    #         }
    #     }
    # }
